mattpolzin/OpenAPIKit

Tests/OpenAPIKitTests/Path Item/ParameterSchemaTests.swift
=> Add encode/decode tests for parameter schema

Package.swift, Sources/OpenAPIKit/Path Item/Operation.swift, Sources/OpenAPIKit/Schema Object/SchemaObject.swift, Sources/OpenAPIKit/Schema Object/TypesAndFormats.swift, Tests/OpenAPIKitCompatibilitySuite/AtlassianAPI.swift, Tests/OpenAPIKitCompatibilitySuite/GoogleBooksAPI.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift
- Add Google Books API to compatibility suite. 
- Support a few additional things in order to successfully parse Google Books API description.
=> Add Compatibility Suite and fix a few small limitations and bugs in the process

Sources/OpenAPIKit/Schema Object/SchemaObjectContext.swift, Sources/OpenAPIKit/Schema Object/TypesAndFormats.swift, Tests/OpenAPIKitCompatibilitySuite/TomTomAPI.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift
- Add TomTom API to compatibility suite.
- Fix bug with parsing schema examples that are not wrapped in strings.
=> Add to compat suite

Sources/OpenAPIKit/Schema Object/SchemaObjectContext.swift, Tests/OpenAPIKitCompatibilitySuite/PetStoreAPITests.swift, Tests/OpenAPIKitCompatibilitySuite/TomTomAPITests.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift
Fixes https://github.com/mattpolzin/OpenAPIKit/issues/56.
=> support whole number floats decoded as integers

Sources/OpenAPIKit/Encoding and Decoding Errors/DiggingError.swift, Sources/OpenAPIKit/Encoding and Decoding Errors/OperationDecodingError.swift, Sources/OpenAPIKit/Encoding and Decoding Errors/PathDecodingError.swift, Sources/OpenAPIKit/Encoding and Decoding Errors/RequestDecodingError.swift, Sources/OpenAPIKit/Encoding and Decoding Errors/ResponseDecodingError.swift, Sources/OpenAPIKit/Path Item/PathItem.swift, Tests/OpenAPIKitErrorReportingTests/PathsErrorTests.swift
Fixes https://github.com/mattpolzin/OpenAPIKit/issues/51.
=> Fix error messages for nested either decoding errors on Paths.

.github/workflows/codecov.yml, .github/workflows/tests.yml
tests were not being triggered by PRs submitted from forks.
=> try turning tests on for PRs

README.md, Sources/OpenAPIKit/ExternalDocumentation.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/67.
=> README additions/fixes

.github/workflows/codecov.yml, .github/workflows/documentation.yml, Sources/OpenAPIKit/Document.swift, Sources/OpenAPIKit/JSONReference.swift, Sources/OpenAPIKit/Schema Object/TypesAndFormats.swift, Sources/OpenAPIKit/Validator/Validator.swift
Generate documentation and save as Wiki on each merge to master. Add a fair amount of code documentation.
=> documentation generation as wiki

Sources/OpenAPIKit/Schema Object/SchemaObject.swift, Sources/OpenAPIKit/Schema Object/SchemaObjectContext.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/44.
=> add context accessors

Sources/OpenAPIKit/Schema Object/SchemaObjectContext.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/93.
=> make the ordering of required and optional object properties stable.

Tests/OpenAPIKitCompatibilitySuite/GoogleBooksAPITests.swift, Tests/OpenAPIKitCompatibilitySuite/PetStoreAPITests.swift, Tests/OpenAPIKitCompatibilitySuite/TomTomAPITests.swift
Also add a few checks to each compatibility test subject.
=> fix Google Books API compat tests after API changed.

Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift
Just adds test coverage for a few more compound schema types with references.
=> add more tests around references within the other compound schema types.

Sources/OpenAPIKit/Header/Header.swift, Tests/OpenAPIKitTests/Header/HeaderTests.swift, Tests/OpenAPIKitTests/Parameter/ParameterTests.swift
Fixes https://github.com/mattpolzin/OpenAPIKit/issues/107.
=> Fix header example decode

Sources/OpenAPIKit/Component Object/Components+JSONReference.swift, Sources/OpenAPIKit/Content/DereferencedContent.swift, Sources/OpenAPIKit/Content/DereferencedContentEncoding.swift, Sources/OpenAPIKit/Document/DereferencedDocument.swift, Sources/OpenAPIKit/Document/Document.swift, Sources/OpenAPIKit/Header/DereferencedHeader.swift, Sources/OpenAPIKit/Operation/DereferencedOperation.swift, Sources/OpenAPIKit/Parameter/DereferencedParameter.swift, Sources/OpenAPIKit/Parameter/DereferencedSchemaContext.swift, Sources/OpenAPIKit/Path Item/DereferencedPathItem.swift, Sources/OpenAPIKit/Request/DereferencedRequest.swift, Sources/OpenAPIKit/Response/DereferencedResponse.swift, Sources/OpenAPIKit/Schema Object/DereferencedSchemaObject.swift, Sources/OpenAPIKit/Schema Object/SchemaObject.swift, Sources/OpenAPIKit/Security/DereferencedSecurityRequirement.swift, Tests/OpenAPIKitTests/ComponentsTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/81.
=> merge the two reference error types.

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift, Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaFragment+Resolving.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaFragment.swift, Tests/OpenAPIKitTests/Schema Object/DereferencedSchemaObjectTests.swift, Tests/OpenAPIKitTests/Schema Object/SchemaFragmentResolvingTests.swift, Tests/OpenAPIKitTests/Schema Object/SchemaFragmentTests.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift, documentation/schema_object.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/123.
=> renamed types and also a few files with incongruous names.

Sources/OpenAPIKit/Server.swift, Tests/OpenAPIKitCompatibilitySuite/GoogleBooksAPITests.swift, Tests/OpenAPIKitTests/ServerTests.swift
Fixes https://github.com/mattpolzin/OpenAPIKit/issues/132.
=> fix incorrectly required enum property on server variables.

Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaFragment+Resolving.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaFragment.swift, Tests/OpenAPIKitTests/Schema Object/SchemaFragmentResolvingTests.swift
Fixes https://github.com/mattpolzin/OpenAPIKit/issues/136.
=> align required boolean of schema fragments around the required arrays.

Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Sources/OpenAPIKit/Validator/Validation+Builtins.swift, Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift, documentation/validation.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/147.
=> Add optional validation that no JSON schema definitions are empty.

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift, Sources/OpenAPIKit/Schema Object/JSONSchema+Combining.swift, Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/164.
WIP.
=> Add default property to schema object

Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/39.
=> Add additional boolean checks to JSON schema based on each type of schema

Sources/OpenAPIKit/Server.swift, Sources/OpenAPIKit/Validator/Validation+Builtins.swift, Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/131.
=> Add validation that all server template variables are defined.

Sources/OpenAPIKit/Components Object/Components+Locatable.swift, Sources/OpenAPIKit/Components Object/Components.swift, Tests/OpenAPIKitTests/ComponentsTests.swift
- Added `pathItems` to `Components`
- Added tests: `test_pathItems_encode` & `test_pathItems_decode` in `ComponentsTests`
=> Add path items to components

Sources/OpenAPIKit/Security/SecurityScheme.swift, Sources/OpenAPIKit30/Security/SecurityScheme.swift, Tests/OpenAPIKitTests/Security/SecuritySchemeTests.swift
- Added `mutualTLS` to `SecurityScheme`
- Added tests for `mutualTLS`
=> Add mutual tls security scheme

Sources/OpenAPIKit/Callbacks.swift, Tests/OpenAPIKitTests/ComponentsTests.swift, Tests/OpenAPIKitTests/Operation/OperationTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/186.
=> support references to path items in callback object.

README.md, SECURITY.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/225.
=> Adding security standards

Sources/OpenAPIKit/Components Object/Components+Locatable.swift, Sources/OpenAPIKit/Components Object/Components.swift, Sources/OpenAPIKit/Either/Either+Convenience.swift, Sources/OpenAPIKit/Link.swift, Sources/OpenAPIKit/Operation/Operation.swift, Sources/OpenAPIKit/Response/Response.swift, Sources/OpenAPIKit30/Components Object/Components+Locatable.swift, Sources/OpenAPIKit30/Components Object/Components.swift, Sources/OpenAPIKit30/Either/Either+Convenience.swift, Sources/OpenAPIKit30/Link.swift, Sources/OpenAPIKit30/Response/Response.swift, Tests/OpenAPIKit30Tests/ComponentsTests.swift, Tests/OpenAPIKit30Tests/LinkTests.swift, Tests/OpenAPIKit30Tests/Response/ResponseTests.swift, Tests/OpenAPIKitCoreTests/Either+CustomStringConvertibleTests.swift, Tests/OpenAPIKitTests/ComponentsTests.swift, Tests/OpenAPIKitTests/LinkTests.swift, Tests/OpenAPIKitTests/Response/ResponseTests.swift, documentation/specification_coverage.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/102.
=> Add Link Object

Sources/OpenAPIKit/Validator/Validation.swift, Sources/OpenAPIKit/Validator/Validator.swift, Sources/OpenAPIKit/_CoreReExport.swift, Sources/OpenAPIKit30/Validator/Validation.swift, Sources/OpenAPIKit30/Validator/Validator.swift, Sources/OpenAPIKit30/_CoreReExport.swift, Sources/OpenAPIKitCore/Encoding and Decoding Errors And Warnings/CodingPathError.swift, Sources/OpenAPIKitCore/Encoding and Decoding Errors And Warnings/OpenAPIWarning.swift, Tests/OpenAPIKit30CompatibilitySuite/GitHubAPITests.swift, Tests/OpenAPIKit30CompatibilitySuite/TomTomAPITests.swift, Tests/OpenAPIKit30ErrorReportingTests/PathsErrorTests.swift, Tests/OpenAPIKit30Tests/Validator/ValidatorTests.swift, Tests/OpenAPIKitErrorReportingTests/PathsErrorTests.swift, Tests/OpenAPIKitTests/Validator/ValidatorTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/243
=> Warnings as errors

Sources/OpenAPIKit/Components Object/Components+Locatable.swift, Sources/OpenAPIKit/Components Object/Components.swift, Sources/OpenAPIKit/Either/Either+Convenience.swift, Sources/OpenAPIKit/Link.swift, Sources/OpenAPIKit/Response/Response.swift, Tests/OpenAPIKitTests/ComponentsTests.swift, Tests/OpenAPIKitTests/LinkTests.swift, Tests/OpenAPIKitTests/Response/ResponseTests.swift, documentation/specification_coverage.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/237.
=> Add Links object

README.md
Hopefully this addresses https://github.com/mattpolzin/OpenAPIKit/issues/266.
=> Add some documentation on using security schemes in OpenAPIKit.

Sources/OpenAPIKit/Content/Content.swift, Sources/OpenAPIKit/Example.swift, Sources/OpenAPIKit30/Content/Content.swift, Sources/OpenAPIKit30/Example.swift, Tests/OpenAPIKit30Tests/Content/ContentTests.swift, Tests/OpenAPIKit30Tests/ExampleTests.swift, Tests/OpenAPIKit30Tests/Parameter/ParameterSchemaTests.swift, Tests/OpenAPIKitTests/Content/ContentTests.swift, Tests/OpenAPIKitTests/ExampleTests.swift, Tests/OpenAPIKitTests/Parameter/ParameterSchemaTests.swift
Fixes https://github.com/mattpolzin/OpenAPIKit/issues/286.
=> make value optional for Example Objects

Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Sources/OpenAPIKit30/Schema Object/JSONSchema.swift, Tests/OpenAPIKit30Tests/Schema Object/JSONSchemaTests.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/292
=> Add extensions to jsonschema

Sources/OpenAPIKit/Header/Header.swift, Sources/OpenAPIKit30/Header/Header.swift, Tests/OpenAPIKit30Tests/Header/HeaderTests.swift, Tests/OpenAPIKitTests/Header/HeaderTests.swift
=> fix explode in header decoding.

Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/241.
=> Support JSON Schema `const`.

Sources/OpenAPIKit/Link.swift, Sources/OpenAPIKit/Response/DereferencedResponse.swift, Sources/OpenAPIKit30/Link.swift, Sources/OpenAPIKit30/Response/DereferencedResponse.swift, Tests/OpenAPIKit30Tests/Response/DereferencedResponseTests.swift, Tests/OpenAPIKitTests/Response/DereferencedResponseTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/293
TODO:
=> Dereference Links

CONTRIBUTING.md, README.md, documentation/v3_migration_guide.md, documentation/validation.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/317.
=> V3 Migration Guide

Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Sources/OpenAPIKit30/Schema Object/JSONSchema.swift, Tests/OpenAPIKit30Tests/Schema Object/JSONSchemaTests.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/321.
TODO:
=> propagate nullability from subschemas where appropriate.

Sources/OpenAPIKitCompat/Compat30To31.swift, Tests/OpenAPIKitCompatTests/DocumentConversionTests.swift
Starting to test the compatibility layer's conversion of json schemas.
=> JSON Schema compatibility conversion testing

CONTRIBUTING.md, README.md, documentation/schema_object.md
Closes https://github.com/mattpolzin/OpenAPIKit/issues/318.
=> small updates to the README documents in preparation for a v3 release

Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift, Sources/OpenAPIKit/_CoreReExport.swift, Sources/OpenAPIKit30/Schema Object/JSONSchemaContext.swift, Sources/OpenAPIKit30/_CoreReExport.swift, Sources/OpenAPIKitCompat/Compat30To31.swift, Sources/OpenAPIKitCore/Shared/JSONSchemaSimpleContexts.swift, Tests/OpenAPIKitCompatTests/DocumentConversionTests.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Closes https://github.com/mattpolzin/OpenAPIKit/issues/331.
=> Media Type and Encoding on JSONSchema

Sources/OpenAPIKit/Validator/Validation+Builtins.swift, Sources/OpenAPIKit/Validator/Validator.swift, Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift
- Fixes typos for serverVarialbeEnumIsValid and serverVarialbeDefaultExistsInEnum
=> Fix typos for serverVarialbeEnumIsValid and serverVarialbeDefaultExistsInEnum

Package.resolved, Package.swift, Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift
=> Raise minimum Yams version.

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift, Sources/OpenAPIKit/Schema Object/JSONSchema.swift, Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift, Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Related to https://github.com/mattpolzin/OpenAPIKit/issues/359.
=> Add JSON Schema `$defs` encoding & decoding

Sources/OpenAPIKitCore/Shared/Path.swift, Tests/OpenAPIKitTests/Path Item/PathItemTests.swift
=> Fix and test for handling of path "/"

Sources/OpenAPIKit/Document/Document.swift, Tests/OpenAPIKitTests/Document/DocumentTests.swift
=> Support OAS 3.1.2
