Package.resolved
Sources/OpenAPIKit/ContentType.swift
Sources/OpenAPIKit/Response.swift
Tests/OpenAPIKitCompatibilitySuite/GoogleBooksAPI.swift
Tests/OpenAPIKitCompatibilitySuite/TomTomAPI.swift

OrderedDictionary was quietly failing to decode keys. Now it is loud. This allowed the existing compatibility suite to bring to light a couple of shortcomings in status code and content type decoding which are fixed by this PR.

Pull in key decoding fix and apply follow-up fixes.

---

Sources/OpenAPIKit/Either/Either.swift
Sources/OpenAPIKit/Schema Conformances/SchemaProtocols.swift
Sources/OpenAPIKit/Schema Conformances/SwiftPrimitiveTypes+OpenAPI.swift
Tests/OpenAPIKitTests/Schema Conformances/SwiftPrimitiveTypes+OpenAPITests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift

⚠️ Breaking Changes ⚠️ 
The throwing `openAPISchema()` function has been changed to the `openAPISchema` property (which is, naturally, non-throwing) because this function never needed to throw anyway in the end. It has been quite a few versions since any code relied on a throwing variant of it.

Change throwing schema function to schema property accessor.

---

Sources/OpenAPIKit/AnyCodable/AnyCodable.swift
Sources/OpenAPIKit/Schema Object/SchemaObject.swift
Sources/OpenAPIKit/Schema Object/SchemaObjectContext.swift
Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift

⚠️ Breaking Changes ⚠️ 
`JSONSchema` `example` properties switched from `String` to `AnyCodable`. This aligns with the examples of the Example Object (`OpenAPI.Example`). `AnyCodable` is preferable here because it will get encoded as a JSON structure instead of a String and that will be presented more favorably in UIs such as ReDoc. Any `Encodable` thing can still be turned into a String and passed in to produce the result that you used to get, the work to do so is just a bit more exposed.

switch to AnyCodable for example in JSONSchema as was always preferable.

---

.github/workflows/codecov.yml
Sources/OpenAPIKit/Components.swift
Sources/OpenAPIKit/Either/Either.swift
Sources/OpenAPIKit/Encoding and Decoding Errors/DocumentDecodingError.swift
Sources/OpenAPIKit/OrderedDictionary/OrderedDictionary.swift
Sources/OpenAPIKit/OrderedDictionary/StringConvertibleHintProvider.swift
Tests/OpenAPIKitErrorReportingTests/ComponentErrorTests.swift
Tests/OpenAPIKitTests/ComponentsTests.swift
Tests/OrderedDictionaryTests/OrderedDictionaryTests.swift

Add ability to provide better error reporting when failing to decode a `LosslessStringConvertible` or `RawRepresentable` key of an `OrderedDictionary`. Use that support to improve error reporting of keys in components dictionaries.
Fixes bug with OrderedDictionary tests as well.

Ordered dictionary improvements

---

Sources/OpenAPIKit/ContentType.swift
Tests/OpenAPIKitTests/ContentTests.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/46.
- add a new `.other` case
- rename the wildcard types to be 'any' instead of 'all'.
- `all` -> `any`
- `applicationAll` -> `anyApplication`
- `audioAll` -> `anyAudio`
- `imageAll` -> `anyImage`
- `textAll` -> `anyText`
- `videoAll` -> `anyVideo`

allow content types that are not pre-specified

---

Sources/OpenAPIKit/Schema Object/JSONSchemaFragment.swift
Sources/OpenAPIKit/Schema Object/SchemaObject.swift
Sources/OpenAPIKit/Schema Object/SchemaObjectContext.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/52.
`JSONSchema` did not have the flexibility to represent the fragments of schemas that are possible when using the `JSONSchema.all(of:)` case. This PR introduces `JSONSchemaFragment` to address that limitation.
⚠️ Breaking Change ⚠️ 
`JSONSchema.all(of:)` used to store an array of `JSONSchema` whereas now it stores an array of `JSONSchemaFragment`.

handle schema fragments

---

Sources/OpenAPIKit/Schema Object/JSONSchemaFragment.swift
Sources/OpenAPIKit/Schema Object/SchemaObject.swift
Tests/OpenAPIKitCompatibilitySuite/PetStoreAPITests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/50.
Change decoding logic such that `JSONSchema` parsing succeeds as long as it is possible to determine which type of schema is being parsed, regardless of whether that type is explicitly specified in the schema.

Fix bug with decoding schemas that have no 'type' property

---

README.md
Sources/OpenAPIKit/CodableVendorExtendable.swift
Sources/OpenAPIKit/Component Object/Components.swift
Sources/OpenAPIKit/Content/Content.swift
Sources/OpenAPIKit/Document.swift
Sources/OpenAPIKit/DocumentInfo.swift
Sources/OpenAPIKit/Example.swift
Sources/OpenAPIKit/Operation.swift
Sources/OpenAPIKit/Parameter/Parameter.swift
Sources/OpenAPIKit/PathItem.swift
Sources/OpenAPIKit/Request.swift
Sources/OpenAPIKit/Response.swift
Sources/OpenAPIKit/SecurityScheme.swift
Sources/OpenAPIKit/Server.swift
Tests/OpenAPIKitTests/RequestTests.swift
Tests/OpenAPIKitTests/ResponseTests.swift
Tests/OpenAPIKitTests/SecuritySchemeTests.swift
Tests/OpenAPIKitTests/ServerTests.swift
Tests/OpenAPIKitTests/VendorExtendableTests.swift

Add vendor extension support to:
- `OpenAPI.Request`
- `OpenAPI.Response`
- `OpenAPI.SecurityScheme`
- `OpenAPI.Server.Variable`

More vendor extension support

---

README.md
Sources/OpenAPIKit/ExternalDocumentation.swift
Sources/OpenAPIKit/Header.swift
Sources/OpenAPIKit/Tag.swift
Tests/OpenAPIKitTests/ExternalDocumentationTests.swift
Tests/OpenAPIKitTests/HeaderTests.swift
Tests/OpenAPIKitTests/TagTests.swift

Add vendor extension support to:
- `OpenAPI.ExternalDocumentation`
- `OpenAPI.Header`
- `OpenAPI.Tag`

Add vendor extensions to external documentation, header, and tag types.

---

Sources/OpenAPIKit/Document.swift
Sources/OpenAPIKit/DocumentInfo.swift
Sources/OpenAPIKit/Example.swift
Sources/OpenAPIKit/Operation.swift
Sources/OpenAPIKit/PathItem.swift
Sources/OpenAPIKit/Server.swift
Tests/OpenAPIKitTests/DocumentTests.swift

- Adds `routes` accessor on `OpenAPI.Document` to retrieve an array of pairings of `Path` and `PathItem`.
- Changes remaining places where initializers used default Xcode indentation.

Get all routes

---

Sources/OpenAPIKit/Document.swift
Sources/OpenAPIKit/Server.swift
Tests/OpenAPIKitTests/DocumentTests.swift

Adds an accessor on `OpenAPI.Document` that collects all servers from anywhere in the document.

Get all servers

---

Sources/OpenAPIKit/Component Object/Components+JSONReference.swift

This is unfortunately technically a breaking change, but I am considering it a patch bug fix because the change is very isolated: `forceDereference()` on `OpenAPI.Components` exists specifically to dereference or error out _instead_ of returning an optional value and, in fact, it was not possible for it to return an optional value, but by sheer typo return was in fact marked optional.

Fix optionality bug

---

Sources/OpenAPIKit/Document/DocumentInfo.swift
Sources/OpenAPIKit/ExternalDocumentation.swift
Sources/OpenAPIKit/Security/OAuthFlows.swift
Sources/OpenAPIKit/Security/SecurityScheme.swift
Sources/OpenAPIKit/Server.swift
Sources/OpenAPIKit/Utility/Container+DecodeURLAsString.swift
Sources/OpenAPIKit/XML.swift
Tests/OpenAPIKitCompatibilitySuite/GoogleBooksAPITests.swift
Tests/OpenAPIKitTests/Document/DocumentInfoTests.swift
Tests/OpenAPIKitTests/ExternalDocumentationTests.swift
Tests/OpenAPIKitTests/Validator/ValidatorTests.swift

Many encoding/decoding libraries appear to encode/decode `URL` as a keyed dictionary, which I can only assume is the default offered by `URL` itself. Foundation JSONEncoder/JSONDecoder is smarter somehow and it encodes/decodes URLs as string values.
Nevertheless, to support more encoder/decoder options without any cost to functionality or hardly any cost to complexity, this PR explicitly encodes URLs to string values and decodes them from string values.

Fixing urls for non foundation coders

---

Sources/OpenAPIKit/CodableVendorExtendable.swift
Tests/OpenAPIKitErrorReportingTests/RequestContentMapErrorTests.swift

Invalid vendor extensions result in an `InconsistencyError`. The error previously just stated that _some_ vendor extension did not begin with the "x-" prefix but now it will print a list of invalid property names.

Improve error for invalid vendor extensions

---

Sources/OpenAPIKit/Operation/Operation.swift
Tests/OpenAPIKitCompatibilitySuite/SwaggerDocSamplesTests.swift
Tests/OpenAPIKitTests/Operation/OperationTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/113.

Ignore operation callbacks instead of failing to decode.

---

Sources/OpenAPIKit/Content/Content.swift
Sources/OpenAPIKit/Content/DereferencedContent.swift
Tests/OpenAPIKitCompatibilitySuite/PetStoreAPITests.swift
Tests/OpenAPIKitCompatibilitySuite/SwaggerDocSamplesTests.swift
Tests/OpenAPIKitErrorReportingTests/RequestContentMapErrorTests.swift
Tests/OpenAPIKitTests/Content/ContentTests.swift
Tests/OpenAPIKitTests/Header/DereferencedHeaderTests.swift
Tests/OpenAPIKitTests/Parameter/DereferencedParameterTests.swift
Tests/OpenAPIKitTests/Request/DereferencedRequestTests.swift
Tests/OpenAPIKitTests/Response/DereferencedResponseTests.swift
Tests/OpenAPIKitTests/Validator/ValidatorTests.swift
documentation/validation.md

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/115.

Make the Content type (aka Media Item Object) schema property not required

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Tests/OpenAPIKitCompatibilitySuite/SwaggerDocSamplesTests.swift
Tests/OpenAPIKitTests/Schema Object/DereferencedSchemaObjectTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaObjectTests.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/143.
The `all(of:)`, `any(of:)`, `one(of:)`, and `not` JSON Schema cases in OpenAPIKit used to only support an optional discriminator as metadata directly on the schema component containing the compound property. Now they all support the full `CoreContext` (with any format) so that `title`, `description`, etc. can be specified on them.
This kind of thing was not previously representable in OpenAPIKit:
```json
{
"title": "a compound thing",
"oneOf": [
...
]
}
```
This is a breaking change for the aforementioned cases on `JSONSchema`. 
If you previously matched on `.not(let schema)`, you now must match on `.not(let schema, core: let coreContext)`.
If you previously matched on `.any(of: let schemas, discriminator: let discriminator)` (or …

Support more context on compound schema types.

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit/Schema Object/SimplifiedJSONSchema.swift
Tests/OpenAPIKitCompatibilitySuite/SwaggerDocSamplesTests.swift
Tests/OpenAPIKitTests/Schema Object/DereferencedSchemaObjectTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentCombiningTests.swift

What was called "resolving" JSON Schemas and was simply done as part of dereferencing is now an explicit separate step you can take on any `JSONSchema`. This PR adds the `simplified()` method to `DereferencedJSONSchema` and the `simplified(given:)` method to `JSONSchema`.

allow dereferenced JSON schemas to still contain allOf components

---

documentation/schema_object.md
documentation/v2_migration_guide.md

Finish off the migration guide and add some documentation on schema simplification to the Schema Object readme file.

Finish migration guide.

---

Sources/OpenAPIKit/Validator/Validation+Builtins.swift
Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift

The message was a bit cryptic in one specific situation that the validation will fail.

Add a bit more information to the schemaComponentsAreDefined validation error message.

---

Sources/OpenAPIKit/Encoding and Decoding Errors/ResponseDecodingError.swift
Sources/OpenAPIKit/Header/Header.swift
Sources/OpenAPIKit/Parameter/Parameter.swift
Tests/OpenAPIKitCompatibilitySuite/GitHubAPITests.swift
Tests/OpenAPIKitErrorReportingTests/ComponentErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/PathsErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/ResponseErrorTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/156.
There was an assumption about OpenAPI structure that does not hold for responses in the components object. That assumption has been removed. I also made a couple of decoding errors a bit more clear in the process.

Fix crash on decoding error for responses within components object.

---

Sources/OpenAPIKit/Document/Document.swift
Sources/OpenAPIKit/Either/Either.swift
Sources/OpenAPIKit/Header/Header.swift
Sources/OpenAPIKit/OrderedDictionary/OrderedDictionary.swift
Sources/OpenAPIKit/Path Item/PathItem.swift
Sources/OpenAPIKit/Validator/Validator+Convenience.swift
Tests/OpenAPIKitTests/Document/DocumentTests.swift
Tests/OpenAPIKitTests/Validator/Validation+ConvenienceTests.swift

- add `lookup()` and `unwrapAndLookup()` validation helpers.
- add `filteringPaths()` to `OpenAPI.PathItem.Map` to make it a bit easier to filter paths out and still have a path item map after you're done (instead of an array of key/value pairs).

Misc. additions

---

Sources/OpenAPIKit/Validator/Validation+Builtins.swift
Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift

Thanks for making such a nice abstraction around OpenAPI, @mattpolzin. I'm using it to great effect for generating a [specification for the Swift registry server interface](https://github.com/mattt/swift-package-registry-oas).
I recently noticed this typo, and thought I'd send a quick patch over.

Fix typo 'unqiue' -> 'unique'

---

Sources/OpenAPIKit/Document/Document.swift
Tests/OpenAPIKitErrorReportingTests/ComponentErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/DocumentErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/JSONReferenceErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/OperationErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/PathsErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/RequestContentMapErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/RequestContentSchemaErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/RequestErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/ResponseErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/SecuritySchemeErrorTests.swift
Tests/OpenAPIKitTests/Document/DocumentTests.swift
Tests/OpenAPIKitTests/EaseOfUseTests.swift
Tests/OpenAPIKitTests/Validator/ValidatorTests.swift

The `Version` enum needed to be changed to disallow 3.0.x and add 3.1.0

update OpenAPI spec versions

---

.github/workflows/documentation.yml
.github/workflows/tests.yml
Package.resolved
Package.swift
README.md
Tests/OpenAPIKitTests/Operation/OperationTests.swift
Tests/OpenAPIKitTests/TestHelpers.swift
Tests/OrderedDictionaryTests/OrderedDictionaryTests.swift

- Switch to using Yams for all order-dependent test cases (which removes the second test-only dependency from the package manifest).
- Add a Swift 5.4 nightly step to CI.

Remove FineJSON test requirement

---

.github/workflows/tests.yml

As noted in #224, OpenAPIKit fails to build on Linux using Swift 5.4.
The workaround documented in #224 to pass the `-Xswiftc -Xfrontend -Xswiftc -sil-verify-none` is gladly no longer needed for the latest nightly builds of Swift 5.5 👍
This is verified [by the GitHub Action run](https://github.com/PSchmiedmayer/OpenAPIKit/actions/runs/1163126009) documented in my fork at: https://github.com/PSchmiedmayer/OpenAPIKit .
This PR adds the corresponding builds to the Test GitHub Action to verify that behavior in the main repo. This PR therefore somehow closes #224 as a future Swift version will solve that issue. 
It also solves the issue in our Apodini and we will remove the additional flags in a corresponding PR as well: Apodini/Apodini#344

Update GitHub Action to Test on Swift 5.5 and Higher

---

.github/workflows/codecov.yml
.github/workflows/tests.yml
Sources/OpenAPIKitCore/OrderedDictionary/OrderedDictionary.swift

- Updates CI to use released 5.5 Docker images.
- Adopts performance improvement to `contains` in `OrderedDictionary` suggested in https://github.com/mattpolzin/OpenAPIKit/issues/232.

Ordered dict contains

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentCombiningTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentTests.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/201.
⚠️ Breaking Change ⚠️ 
The OpenAPIKit module (but not the OpenAPIKit30 module) now exposes only an `examples` property on `JSONSchema`s and their contexts. This is backwards compatible with `example` when decoding, but code that references `example` will need to be updated to use the new `examples` array instead.

Json schema `examples` support

---

Sources/OpenAPIKit/CodableVendorExtendable.swift
Sources/OpenAPIKit30/CodableVendorExtendable.swift

I know it's not pretty, but it gets the job done.
My measurements (Release Mode, Yams, GitHub spec with 75K lines):
**Before:** Parse spec completed (2.507 s)
**After:** Parse spec completed (0.793 s)
That's more than three times faster!
It's not ideal to have to disable it manually every time. I'm thinking, is there a way to detect upfront whether extensions are needed? I wish spec had some metadata.

Add an option to disable vendor extensions

---

Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Sources/OpenAPIKit30/Schema Object/JSONSchemaContext.swift

I've tested OpenAPIKit with over 400k lines of OpenAPI specs. The most common issue I've encountered so far has to do with string enums and allowed values and the interplay of `OpenAPIKit.AnyCodable`, `Yams`, and `Double`. Here are a couple of examples:
```yaml
searcherKey:
type: string
enum:
- com.atlassian.jira.plugin.system.customfieldtypes:cascadingselectsearcher
...
```
I get `AnyCodable` with value `0` of type `Int` in the allowed values.
It happens because of the sexagesimal [support in Yams](https://github.com/jpsim/Yams/issues/337). When [it sees](https://github.com/jpsim/Yams/blob/9ff1cc9327586db4e0c8f46f064b6a82ec1566fa/Sources/Yams/Constructor.swift#L302) ":" in a value, it assumes it's a number. I think it's supposed to bail out when it sees it has letters, but it doesn't and …

Add a hint when decoding allowedValues

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Sources/OpenAPIKit30/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit30/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit30/Schema Object/JSONSchema.swift
Sources/OpenAPIKit30/Schema Object/JSONSchemaContext.swift
Tests/OpenAPIKit30Tests/Schema Object/SchemaFragmentCombiningTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentCombiningTests.swift

Specs are often designed with a particular order of properties in mind.
I haven't updated the tests yet – there are a few that are now failing.

Keep properties order in objects

---

Sources/OpenAPIKit/Response/Response.swift
Sources/OpenAPIKit30/Response/Response.swift
Tests/OpenAPIKit30Tests/Response/ResponseTests.swift
Tests/OpenAPIKitTests/Response/ResponseTests.swift

⚠️ Breaking Change ⚠️ 
`Response.StatusCode` is changing from an enum to a struct. Code won't necessarily need to change, but switching on it will need to instead switch on its `value` property.

status code warning becomes a real warning.

---

Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift

Cherry-pick of https://github.com/mattpolzin/OpenAPIKit/pull/245 🍒

Add a hint for allowed values types

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Sources/OpenAPIKit/Schema Object/TypesAndFormats.swift
Sources/OpenAPIKit30/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit30/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit30/Schema Object/JSONSchema.swift
Sources/OpenAPIKit30/Schema Object/TypesAndFormats.swift
Tests/OpenAPIKit30CompatibilitySuite/PetStoreAPITests.swift
Tests/OpenAPIKit30ErrorReportingTests/PathsErrorTests.swift
Tests/OpenAPIKit30Tests/Schema Object/JSONSchemaTests.swift
Tests/OpenAPIKit30Tests/Schema Object/SchemaFragmentTests.swift
Tests/OpenAPIKit30Tests/Validator/ValidatorTests.swift
Tests/OpenAPIKitErrorReportingTests/PathsErrorTests.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentTests.swift
Tests/OpenAPIKitTests/Validator/ValidatorTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/239
⚠️ Breaking Changes ⚠️ 
`JSONSchema` changes from an enum to a struct (as usual, to facilitate storage of warnings). For most code, use will not change, but if you switch over any `JSONSchemas`, you should change to switching over the newly exposed `value` property of `JSONSchema`.

JSONSchema warnings

---

Package.swift

As discussed in https://github.com/mattpolzin/OpenAPIKit/issues/259, this extends the range of Yams versions supported on the main branch.

Update Yams to support versions 4.x.x and 5.x.x

---

Package.swift

As discussed in https://github.com/mattpolzin/OpenAPIKit/issues/259, this extends the range of Yams versions supported on the v3 branch.

Update Yams to support versions 4.x.x and 5.x.x (v3 branch)

---

Sources/OpenAPIKit/Path Item/PathItem.swift
Tests/OpenAPIKitTests/Path Item/PathItemTests.swift

Addresses an issue found in downstream project for OpenAPIKit 2.x: https://github.com/apple/swift-openapi-generator/issues/51

support trailing slashes in paths (which are sometimes required by APIs)

---

Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift

Simplified `allOf` schemas were not taking on the correct optionality (they were always required) because the root `allOf` context was being marked optional but all of its fragments were being left required and combination of fragments starts with an optional assumption and flips to required the first time a required fragment is encountered.

Fix simplified allOf schema optionality

---

Sources/OpenAPIKit/JSONReference.swift
Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Sources/OpenAPIKitCompat/Compat30To31.swift
Sources/OpenAPIKitCore/Shared/JSONSchemaSimpleContexts.swift
Tests/OpenAPIKitTests/JSONReferenceTests.swift
Tests/OpenAPIKitTests/Schema Object/DereferencedSchemaObjectTests.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/298.
**Implementation**
This PR replaces the `JSONSchema` `reference` case's `ReferenceContext` with a `CoreContext` (only for the `OpenAPIKit` module, not the `OpenAPIKit30` module) and it uses that core context's `description` to override the `description` within a referenced schema when calling the `dereferenced()` or `dereferenced(in:)` methods on `JSONSchema`. This carries through, naturally, to dereferencing performed on parent values all the way up to the execution of `locallyDereferenced()` on `OpenAPI.Document`.
There is also a new `openAPIReference(withDescription description: String? = nil)` method on `JSONReference` to make it easy to elevate a `JSONReference` to an `OpenAPI.Reference`. OpenAPIKit does not use this …

Support schema reference description overrides

---

Sources/OpenAPIKit/Header/Header.swift
Tests/OpenAPIKitTests/Header/HeaderTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/300.

fix bug where headers were not allowed to define explode when decoding

---

Sources/OpenAPIKit/Encoding and Decoding Errors/PathDecodingError.swift
Sources/OpenAPIKit/Operation/Operation.swift
Sources/OpenAPIKit/Validator/Validation+Builtins.swift
Sources/OpenAPIKit/Validator/Validator.swift
Sources/OpenAPIKit30/Encoding and Decoding Errors/PathDecodingError.swift
Sources/OpenAPIKitCore/Encoding and Decoding Errors And Warnings/DiggingError.swift
Tests/OpenAPIKit30Tests/Validator/BuiltinValidationTests.swift
Tests/OpenAPIKitErrorReportingTests/OperationErrorTests.swift
Tests/OpenAPIKitErrorReportingTests/PathsErrorTests.swift
Tests/OpenAPIKitTests/ComponentsTests.swift
Tests/OpenAPIKitTests/Document/DocumentTests.swift
Tests/OpenAPIKitTests/Operation/OperationTests.swift
Tests/OpenAPIKitTests/Path Item/PathItemTests.swift
Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift
documentation/validation.md

Closes https://github.com/mattpolzin/OpenAPIKit/issues/193.
Todo:

apply optional responses changes to OpenAPIKit module.

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema+Combining.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Tests/OpenAPIKitTests/Schema Object/DereferencedSchemaObjectTests.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaFragmentCombiningTests.swift

There are some keywords (and also the concept of "required") that need to exist for `null` schemas just like any other schema types.

Add context for `null` schemas

---

Sources/OpenAPIKitCore/Shared/Discriminator.swift

Hi 👋 
Thank you for creating this library!
Im generating a OpenAPISpec in code then encode it using `Yams` which preserves the order in which keys are encoded.
Since the order of keys of a `Swift.Dictionary` is not stable the generated api-spec always has some small diffs (the mapping of the discriminator is reordered)
This addresses this by using a `OrderedDictionary`

Use `OrderedDictionary` for discriminator mapping

---

Sources/OpenAPIKitCompat/Compat30To31.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/328.

make private helpers private again.

---

.github/workflows/codecov.yml
.github/workflows/tests.yml
Package.swift

Closes https://github.com/mattpolzin/OpenAPIKit/issues/313

Drop support for Swift versions prior to 5.8

---

Sources/OpenAPIKit/Encoding and Decoding Errors/DocumentDecodingError.swift
Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Sources/OpenAPIKit30/Encoding and Decoding Errors/DocumentDecodingError.swift
Sources/OpenAPIKit30/Schema Object/JSONSchemaContext.swift
Sources/OpenAPIKitCore/Encoding and Decoding Errors And Warnings/InconsistencyError.swift
Tests/OpenAPIKit30ErrorReportingTests/SchemaErrorTests.swift
Tests/OpenAPIKit30Tests/Schema Object/JSONSchemaTests.swift
Tests/OpenAPIKit30Tests/Schema Object/SchemaObjectYamsTests.swift
Tests/OpenAPIKitErrorReportingTests/SchemaErrorTests.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift
Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift

Fixes a bug where decoding max or min 64 bit integer values would fail when being done via Double.

Improve integer max/min parsing and inconsistency errors

---

Sources/OpenAPIKitCompat/Compat30To31.swift
Tests/OpenAPIKitCompatTests/DocumentConversionTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/345

Fix bug with conversion dropping explode property of parameters

---

README.md
Sources/OpenAPIKitCore/AnyCodable/AnyCodable.swift
Tests/AnyCodableTests/AnyCodableTests.swift

- Improve equality checking of `AnyCodable` to handle more cases.
- Support encoding any `Codable` wrapped in `AnyCodable`.
- Improve documentation of `AnyCodable` limitations regarding equality through a full encode -> decode cycle.

Improvements to AnyCodable equality and ability to Encode any Encodable.

---

Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Sources/OpenAPIKit30/Schema Object/JSONSchemaContext.swift
Tests/OpenAPIKitCompatTests/DocumentConversionTests.swift

The inferred-ness of a schema was being lost when using helper functions to modify single properties of that schema's core context.
This PR fixes that bug.

keep inferred when updating any other property of a core context using a helper function

---

Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Tests/OpenAPIKitErrorReportingTests/SchemaErrorTests.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift

The `"nullable"` keyword is inconsistently handled. Decoding logic exists, but when the `"type"` keyword is recognized, the `[..., "null"]` array pattern takes precedence. This change fixes that, so both work.

fix "nullable" decoding

---

.github/workflows/documentation.yml
Package.resolved
Package.swift
README.md

Closes https://github.com/mattpolzin/OpenAPIKit/issues/338.

Add swift docc based documentation to repo via GitHub pages.

---

Sources/OpenAPIKit/Schema Object/DereferencedJSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift

This PR adds backwards compatible support for _parsing_ `$anchor` and `$dynamicAnchor` properties of `JSONSchema`s. It does not integrate those new properties with any additional functionality yet.
Related to https://github.com/mattpolzin/OpenAPIKit/issues/359.

Add JSONSchema support for anchors

---

.github/workflows/codecov.yml
.github/workflows/documentation.yml
.github/workflows/tests.yml
Sources/OpenAPIKit/Content/ContentEncoding.swift
Tests/OpenAPIKitTests/Content/ContentTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/378.

Add support for multiple content types on one content encoding object

---

.github/workflows/tests.yml
Sources/OpenAPIKit/Content/ContentEncoding.swift
Sources/OpenAPIKit/Content/DereferencedContentEncoding.swift
Sources/OpenAPIKit/Schema Object/JSONSchemaContext.swift
Sources/OpenAPIKitCompat/Compat30To31.swift
Tests/OpenAPIKitCompatTests/DocumentConversionTests.swift
Tests/OpenAPIKitTests/Content/ContentTests.swift

The Content Encoding Object's `contentType` (singular) property was deprecated in v3.2.0 and has now been removed in favor of `contentTypes` (plural).
The default implementations of `inferred`, `anchor`, and `dynamicAnchor` in the `JSONSchemaContext` have been removed. They were only there to make any third party conformances to `JSONSchemaContext` non-breaking. 99% of code will not change as a result of this.

Remove deprecated contentType property

---

Sources/OpenAPIKitCore/URLTemplate/URLTemplate+Parsing.swift
Sources/OpenAPIKitCore/URLTemplate/URLTemplate.swift
Tests/OpenAPIKitCoreTests/URLTemplate/URLTemplateTests.swift

Fixes https://github.com/mattpolzin/OpenAPIKit/issues/382.
Just a straight forward conversion from recursive function to loop.

Fix `URLTemplate` stack overflow

---

Sources/OpenAPIKit/Validator/Validation+Builtins.swift
Sources/OpenAPIKit/Validator/Validator.swift

I've made sure to introduce the fixed spellings as new symbols and add deprecation warnings with Fit-Its on the existing symbols so this is not a breaking change and won't require a major version bump; though the upcoming 4.x could be a good time to completely remove the misspelt symbols.

Fix typo in symbol name for server variable validations

---

Sources/OpenAPIKit/Document/Document.swift
Sources/OpenAPIKit30/Document/Document.swift
Sources/OpenAPIKitCompat/Compat30To31.swift

New OAS versions dropped with no need to update code other than to indicate the versions are supported.
https://www.openapis.org/blog/2024/10/25/announcing-openapi-specification-patch-releases

Add support for new patch versions of OAS

---

Sources/OpenAPIKit/Document/DocumentInfo.swift

I'm working on a project that requires lots of individual mutation of the entire Document structure, and I couldn't find a particular reason why all the Document.Info fields are immutable. The rest of the Document structure seems to be mutable. Wondering if there's something I'm overlooking. Thanks so much for this awesome package 😀

Make Document.Info members mutable

---

Sources/OpenAPIKit/Document/Document.swift
Sources/OpenAPIKit30/Document/Document.swift
Tests/OpenAPIKit30Tests/Document/DocumentTests.swift
Tests/OpenAPIKitTests/Document/DocumentTests.swift
documentation/v4_migration_guide.md

Closes https://github.com/mattpolzin/OpenAPIKit/issues/395

Support future OAS versions without breaking enum changes

---

Sources/OpenAPIKit/Content/ContentEncoding.swift
Sources/OpenAPIKit30/Content/ContentEncoding.swift
Tests/OpenAPIKit30Tests/Content/ContentTests.swift
Tests/OpenAPIKitTests/Content/ContentTests.swift

Issue #315 
This PR adds vendor extension support to the Content.Encoding type, addressing issue #315. The implementation follows the existing patterns used throughout the codebase for vendor extensions.
Changes made:
- Added VendorExtendable protocol conformance to Content.Encoding
- Introduced vendorExtensions property to store custom extensions
- Updated initializers to support optional vendor extensions
- Modified CodingKeys to properly handle vendor extension encoding/decoding
- Added comprehensive test cases for both encoding and decoding of vendor extensions
The changes are non-breaking as they:
- Maintain backward compatibility with existing code
- Make vendorExtensions parameter optional with a default empty dictionary
- Preserve all existing functionality
I've implemented these …

Add vendor extension support to Content.Encoding type

---

Sources/OpenAPIKit/Validator/Validation+Builtins.swift
Sources/OpenAPIKit30/Validator/Validation+Builtins.swift
Tests/OpenAPIKit30Tests/Validator/BuiltinValidationTests.swift
Tests/OpenAPIKitTests/Validator/BuiltinValidationTests.swift

Issue #236 
This PR directly addresses the issue mentioned in the GitHub project (issue #236) for OpenAPIKit.
I have added a validation that ensures operationIds in Link objects refer to actual Operations that exist in the document. 
Changes
1. I've created a new optional validation called linkOperationsExist that verifies Link objects with operationIds are pointing to valid Operations in the document.
2. Extracting the operationId from the Link object (ignoring Links that use operationRef instead)
- Collecting all operationIds from all Operations in the document (using different approaches in OpenAPIKit and OpenAPIKit30)
- Checking if the Link's operationId is contained in the list of valid operationIds
3. When a Link refers to a non-existent operationId, the validation produces a clear …

Added a Validation that checks all operationIds in Link objects are valid

---

Sources/OpenAPIKit/Schema Object/JSONSchema.swift
Tests/OpenAPIKitTests/Schema Object/JSONSchemaTests.swift

Hi, thanks for a great library.
I noticed that for `anyOf` `allOf` `oneOf` schemas the vendor-extensions don't seem to get parsed.
I tweaked the parsing code, that seemed to skip it because of a early return, to handle that, and also added some test.
Please let me know if theres anything else i can contribute

Support vendor extensions in `anyOf` `allOf` `oneOf` for OAS 3.1

---

Sources/OpenAPIKitCore/Shared/ContentType.swift

closes https://github.com/mattpolzin/OpenAPIKit/issues/415

add more ContentType's
